name: Cypress Tests
on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/cypress.yml"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/cypress.yml"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: |
        export DISABLE_ESLINT_PLUGIN=true
        npm run build

    # - name: Run e2e tests
    #   uses: cypress-io/github-action@v5
    #   with:
    #     working-directory: frontend
    #     start: npm start
    #     wait-on: 'http://localhost:3000'
    #     config-file: cypress/e2e-config.json

    - name: Run Cypress component tests
      uses: cypress-io/github-action@v5
      with:
        browser: chrome
        component: true
