name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Check for package-lock.json
      id: check-lock
      run: |
        if [ -f "package-lock.json" ]; then
          echo "lock_exists=true" >> $GITHUB_OUTPUT
        else
          echo "lock_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Install Dependencies (with package-lock.json)
      if: steps.check-lock.outputs.lock_exists == 'true'
      run: npm ci

    - name: Install Dependencies (without package-lock.json)
      if: steps.check-lock.outputs.lock_exists == 'false'
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Start React App
      run: npm start & npx wait-on http://localhost:3000

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v5
      with:
        command: npm run cypress:run
        wait-on: 'http://localhost:3000'
        browser: chrome
        headless: true

    - name: Upload Cypress Screenshots
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots

    - name: Upload Cypress Videos
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos

